databaseType = "MySql"
id = "62978185-052f-46ee-ad78-08fa304e6994"
name = "uaa_db"

[flyway]
callbackLocations = [ "filesystem:callbacks" ]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

[flywayDesktop]
enableMigrations = true
showDeploymentDecision = true
developmentEnvironment = "development"
shadowEnvironment = "shadow"

  [flywayDesktop.generate]
  undoScripts = false

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"

[environments.uaa_db]
url = "jdbc:mysql://localhost:3306?allowPublicKeyRetrieval=true&useSSL=false"
schemas = [ "uaa_db" ]
